name = "EcoNetDynOutputs"
uuid = "9b7c96af-00f4-4809-8f3b-e928a99f2955"
authors = ["Alain Danet <a.h.danet@sheffield.ac.uk>", "Ismaël Lajaaiti <ismael.lajaaiti@gmail.com>"]
version = "0.1.0"

[deps]
EcologicalNetworksDynamics = "2fd9189a-c387-4076-88b7-22b33b5a4388"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ForwardDiff = "0.10.38"
LinearAlgebra = "1.11.0"
